### ISSUE TITLE
Duration of the processed video is Longer than source video

### ISSUE THREAD

**Issue by o98k-ok** [erikalu/omnimatte#22]
Hi erkalu, I complete all attempts about default video demos and custom demos. But now I have a problem which is the processed video duration  does not match with source video, and the processed video object moves very slowly. I don’t know if there is a problem with my steps.

**Comment by o98k-ok** [comment]
Here is my training result: https://github.com/haoguanguan/simple_demos .
For default video, my operation is:
1. python train.py --name tennis --dataroot ./datasets/tennis --gpu_ids 0
2. python test.py --name tennis --dataroot ./datasets/tennis --gpu_ids 0
That's all, thank you.

**Comment by erikalu** [comment]
This seems to just be a difference in the video framerate. You can use ffmpeg to encode the video with a different fps.

**Comment by o98k-ok** [comment]
> This seems to just be a difference in the video framerate. You can use ffmpeg to encode the video with a different fps.

OK， I will try it. Thanks.
