### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ai1361720220000** [erikalu/omnimatte#3]
hello, when i run the training command, the error occurs. i'm confused about the H0 and H_1 parameters, what's the meaning of these two parameters?

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    main()
  File "train.py", line 42, in main
    train(model, dataset, visualizer, opt)
  File "train.py", line 54, in train
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/notebook/data/personal/80303875/project/omnimatte/omnimatte/third_party/data/__init__.py", line 92, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/notebook/data/personal/80303875/project/omnimatte/omnimatte/data/omnimatte_dataset.py", line 129, in __getitem__
    data_t2 = self.get_transformed_item(index + 1, transform_params)
  File "/home/notebook/data/personal/80303875/project/omnimatte/omnimatte/data/omnimatte_dataset.py", line 194, in get_transformed_item
    bg_flow = self.get_background_flow(index, mask_w, mask_h)  # 2, H, W
  File "/home/notebook/data/personal/80303875/project/omnimatte/omnimatte/data/omnimatte_dataset.py", line 287, in get_background_flow
    H_1 = self.homographies[index + 1]
IndexError: list index out of range

**Comment by erikalu** [comment]
Hi, what data are you training on? Is it the tennis demo or your custom video?

H_0 and H_1 are homographies for the current and next frame, respectively. This error is probably because the homography file isn't formatted correctly.

**Comment by ai1361720220000** [comment]
Thanks for your reply. &nbsp;I used the tennis demo for training the network. &nbsp;Is there any wrong with the origin tennis data in this repos? Also, after I change &nbsp;the parameter&nbsp;max_dataset_size to 70, the code run without error.  
BTW, I have another question. How many epochs does the network run based on the tennis demo?



发自我的iPhone


------------------ Original ------------------
From: Erika Lu ***@***.***&gt;
Date: Mon,Jul 26,2021 10:33 PM
To: erikalu/omnimatte ***@***.***&gt;
Cc: Alxendx ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [erikalu/omnimatte] IndexError: list index out of range (#3)





 
Hi, what data are you training on? Is it the tennis demo or your custom video?
 
H_0 and H_1 are homographies for the current and next frame, respectively. This error is probably because the homography file isn't formatted correctly.

**Comment by erikalu** [comment]
That's strange, I just checked and I don't get this error, even without changing max_dataset_size.

The default number of training steps is 12k (the number of epochs it corresponds to will depend on the batch size you use). You may want to increase the number of training steps if you're using a small batch size.

**Comment by ai1361720220000** [comment]
Emmm it’s very confusing for the error. &nbsp;Also, 12K with batch size of 8 may cost more than 10 hours which is so expensive for a certain experiment. &nbsp;



发自我的iPhone


------------------ Original ------------------
From: Erika Lu ***@***.***&gt;
Date: Mon,Jul 26,2021 11:32 PM
To: erikalu/omnimatte ***@***.***&gt;
Cc: Alxendx ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [erikalu/omnimatte] IndexError: list index out of range (#3)





 
That's strange, I just checked and I don't get this error, even without changing max_dataset_size.
 
The default number of training steps is 12k (the number of epochs it corresponds to will depend on the batch size you use). You may want to increase the number of training steps if you're using a small batch size.

**Comment by erikalu** [comment]
What GPU are you using? It took about 2 hours to run on 2 P100 GPUs.

**Comment by ai1361720220000** [comment]
I run on a Tesla V100



发自我的iPhone


------------------ Original ------------------
From: Erika Lu ***@***.***&gt;
Date: Mon,Jul 26,2021 11:49 PM
To: erikalu/omnimatte ***@***.***&gt;
Cc: Alxendx ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [erikalu/omnimatte] IndexError: list index out of range (#3)





 
What GPU are you using? It took about 2 hours to run on 2 P100 GPUs.

**Comment by ai1361720220000** [comment]
Hello, could you tell how to get zbar.pth for a new dataset. What's the zbar meaning?  i also confused whether zbar would be update if it is set randomly in the network?

**Comment by erikalu** [comment]
zbar.pth is randomly initialized and saved if it doesn't already exist, otherwise the existing file is loaded. These values aren't updated during training. It is random fixed noise that represents the input for the background layer.
